### ISSUE TITLE
拋出異常

### ISSUE THREAD

**Issue by owen800q** [Tsaiboss/decodeObfuscator#1]
/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:24978
                        throw new TypeError(`Property ${n} of ${t.type} expected node to be of a type ${JSON.stringify(e)} but instead got ${JSON.stringify(null == s ? void 0 : s.type)}`);
                        ^

TypeError: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got undefined
    at Object.t [as validate] (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:24978:31)
    at i (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:27958:70)
    at n.default (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:27951:13)
    at I.n._replaceWith (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16954:61)
    at I.n._remove (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16867:25)
    at I.n.remove (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16853:18)
    at n.hooks (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16559:19)
    at I.n._callRemovalHooks (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16861:42)
    at I.n.remove (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/babel_asttool.js:16848:22)
    at VariableDeclarator (/Users/kwan/Programming/Javascript/decodeObfuscator/tools/usefulPlugins.js:340:9)

附上样本

https://gist.github.com/owen800q/bb7e93cba0229f9886a983a47b8f99de

**Comment by Python-time** [comment]
@owen800q 解决了吗，我也遇到了这个错误

**Comment by owen800q** [comment]
@Python-time 沒呢，你找到解決方法了嗎

**Comment by afwfv** [comment]
我也是这个问题

**Comment by codingchenp** [comment]
也是这个问题
